### ISSUE TITLE
Uncomment Mac support

### ISSUE THREAD

**Issue by fulldecent** [droe/rosefs#1]
In rose.c:

```
struct fuse_operations rose_oper = {
...
/*  .getxattr   = rose_op_getxattr, */
```

And other similar functions are commented out. These could be `#ifdef`'ed out to allow support when compiling for Mac.

**Comment by droe** [comment]
Note that this would lead to attributes being stored unencrypted, while in the current solution, OS X falls back to using dot-files (which end up being encrypted as regular files). So commenting it out leads to encrypted attributes without having to implement attribute encryption separately.

**Comment by fulldecent** [comment]
Oh nice! Thanks for explaining this to me. Closing.
